//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public store()
        {
            this.stocklevels = new HashSet<stocklevel>();
        }
    
        public int storeId { get; set; }
        public string storeAddress { get; set; }
        public int storeTel { get; set; }
    
        public virtual ICollection<stocklevel> stocklevels { get; set; }
    }
}
